import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className = "bg-gray-700">
        <header className="bg-sky-400 h-9 text-center text-3xl">Header</header>
        {children}
        <footer className="bg-red-700 h-9 text-center text-3xl;">Footer</footer>
      </body>
    </html>
  )
}
